version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t node-app:latest .
      - docker tag node-app:latest $IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $IMAGE_REPO_NAME:latest
