version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t node-app:latest .
      - docker tag node-app:latest $IMAGE_REPO_NAME:latest
#      - printf '[{"name":"web","imageUri":"%s"}]' $IMAGE_REPO_NAME:latest > imagedefinitions.json
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $IMAGE_REPO_NAME:latest
      - printf '[{"name":"web","imageUri":"%s"}]' $IMAGE_REPO_NAME:latest > $CODEBUILD_SRC_DIR/imagedefinitions.json
artifacts:
    files:
      - imagedefinitions.json
